server:
  port: 8080
#  max-http-header-size: 65536
#  compression:
#    enabled: true
#  tomcat:
#    relaxed-query-chars: '|,{,},[,]'
#  servlet:
#    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway: # migration
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:migration
#    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin
  data:
    redis:
      password: redis
      port: 6379
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  show-actuator: false
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

jwt:
  secret: ez2secret-123456789012345678901234
  expire: 100000000

thread-pool:
  core-pool-size: ${THREADPOOL_CORE:4}
  max-pool-size: ${THREADPOOL_MAX:10}
  queue-capacity: ${THREADPOOL_QUEUE_CAPACITY:100}
  thread-name-prefix: ${THREADPOOL_THREAD_NAME:10}
#  main:
#    allow-bean-definition-overriding: true
#    allow-circular-references: true
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#    multipart:
#      enabled: true
#      max-file-size: 1024MB
#      max-request-size: 2048MB
#      file-size-threshold: 2KB
#  cloud:
#    config:
#      enabled: false
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#
#http:
#  multipart:
#    max-file-size: 1024MB
#    max-request-size: 2048MB
#
#health:
#  config:
#    enabled: true
#management:
#  security:
#    enabled: false
#  health:
#    defaults:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 1
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://${env.eureka.url:localhost}:${env.eureka.port:8001}/eureka/

#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF
#      zaxxer:
#        hikari:
#          HikariConfig: DEBUG
#          nodeValue: DEBUG
#    org:
#      hibernate:
#        SQL: ERROR
#        persister:
#          entity: ERROR
#        type:
#          descriptor:
#            sql:
#              BasicBinder: ERROR



