version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ez_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ez_net

  redis:
    image: redis:7.2
    container_name: ez_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ez_net

volumes:
  mysql_data:
  redis_data:

networks:
  ez_net:
    driver: bridge
